### ISSUE TITLE
Very long type signatures in error messages

### ISSUE THREAD

**Issue by emnh** [Octachron/phantom_algebra#2]
The type signature for even a small expression is very, very long. Check out the second error in http://emh.lart.no/publish/misc/build-log.txt . It's hard to read it and figure out what's wrong.

**Comment by Octachron** [comment]
Ah yes, the error message are very long since the encoding of type-level functions is not particularly efficient in term of type size.

It might be possible to reduce the size, but they are no full solution short of writing an error message plugins that would reinterpret the message with a higher level point of view.

For more pratical solution, I think it would be a good start to recommend opening the Type_functions modules (or even maybe include it in the general interface modules) and reading type error from bottom to top.

**Comment by emnh** [comment]
Ah okay. The problem in this case was with an overloaded function that takes either a vec2 or a vec3 and returns an expression based on that. I resorted to duplicating the expression for each case and that worked. Maybe there is a more general way.

**Comment by emnh** [comment]
The long errors are only a problem with higher order or overloaded functions. Using a flat structure they are quite small and readable and it works well in practice.

**Comment by Octachron** [comment]
Thanks for the feedback! In fact, overloaded functions are quite tricky right now; they may be some way around but I need to check that they are not breaking the type  system.
